# shell tools
brew "tmux"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "jq"

# vim tools
brew "vim"
brew "aspell"
brew "ctags"

# neovim and dependencies
brew "neovim"
brew "ripgrep"
brew "fd"
brew "node"

# search tools
brew "the_silver_searcher"
